avatar_2: # Тот же ID, что был при подготовке
  preparation: FALSE # ТЕПЕРЬ СТАВИМ FALSE
  video_path: "data/video/test2_crop.mp4"
  audio_clips: 
    audio_0: "data/audio/audio_test.wav" # Проверьте, что этот файл существует!
  bbox_shift: 0